matrix:
  include:
    - os: linux
      language: python
      dist: precise
      python:
        - "2.7.15"
      env:
        - GAMOS=linux
        - PLATFORM=x64
    - os: linux
      language: python
      dist: precise
      python:
        - "2.7.15"
      env:
        - GAMOS=linux
        - PLATFORM=x86
    - os: osx
      language: generic
      osx_image: xcode10.1
      env:
        - GAMOS=macos
        - PLATFORM=x64
      addons:
        homebrew:
          packages:
            python@2
    - os: windows
      language: shell
      env:
        - GAMOS=windows
          PLATFORM=x64
    - os: windows
      language: shell
      env:
        - GAMOS=windows
        - CINST_ARGS=--forcex86
        - PLATFORM=x86

before_install:
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
    powershell Install-WindowsFeature Net-Framework-Core;
    cinst -y $CINST_ARGS python2;
    export PATH=$PATH:/c/Python27/scripts;
    cinst -y wixtoolset;
  fi
- pip install pyinstaller

install:
- cd src
- pyinstaller --clean -F --distpath=gam $GAMOS-gam.spec
- cp LICENSE gam
- cp whatsnew.txt gam
- cp GamCommands.txt gam
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
    GAM_ARCHIVE=gam-$TRAVIS_BUILD_NUMBER-$GAMOS-$PLATFORM.zip;
    /c/Program\ Files/7-Zip/7z.exe a -tzip $GAM_ARCHIVE -xr!.svn;
    # FIXME - gam.wxs always expects build in gam-64
    mv gam gam-64
    export GAMVERSION=$TRAVIS_BUILD_NUMBER.0;
    /c/Program\ Files\ \(x86\)/WiX\ Toolset\ v3.11/bin/candle.exe -arch $PLATFORM gam.wxs;
    /c/Program\ Files\ \(x86\)/Wix\ Toolset\ v3.11/bin/light.exe -ext /c/Program\ Files\ \(x86\)/WiX\ Toolset\ v3.11/bin/WixUIExtension.dll gam.wixobj -o gam-$TRAVIS_BUILD_NUMBER-$GAMOS-$PLATFORM.msi;
  else
    GAM_ARCHIVE=gam-$TRAVIS_BUILD_NUMBER-$GAMOS-$PLATFORM.tar.xz;
    tar cfJ $GAM_ARCHIVE gam/;
  fi

script:
- gam/gam version
