language: python
matrix:
  include:
    - os: linux
      dist: precise
      python:
        - "2.7.15"
      env: GAMOS=linux
    - os: osx
      osx_image: xcode9.2
      python:
        - "3.6"
      env: GAMOS=macos
      addons:
        homebrew:
          packages:
            python@2

before_install:
- pip install pyinstaller

install:
- cd src
- pyinstaller --clean -F --distpath=gam $GAMOS-gam.spec
- cp LICENSE gam
- cp whatsnew.txt gam
- cp GamCommands.txt gam
- tar cfJ gam-$TRAVIS_BUILd_NUMBER-$GAMOS.tar.xz gam/

script:
- gam/gam version

deploy:
  skip_cleanup: true
  file: gam-$TRAVIS_BUILd_NUMBER-$GAMOS.tar.xz
