matrix:
  include:
    - os: linux
      language: python
      dist: precise
      python:
        - "2.7.15"
      env:
        - GAMOS=linux
    - os: linux
      language: python
      dist: precise
      python:
        - "2.7.15"
      env: GAMOS=linux
        - GAMOS=linux
        - PLAT=i686
    - os: osx
      language: generic
      osx_image: xcode10.1
      env: GAMOS=macos
      addons:
        homebrew:
          packages:
            python@2
    - os: windows
      language: shell
      env: GAMOS=windows

before_install:
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
    powershell Install-WindowsFeature Net-Framework-Core;
    cinst -y python2;
    cinst -y --forcex86 --installdirectory=c:\Python27-32;
    cinst -y wixtoolset;
    alias python32=/c/Python27-32/python;
  fi
- python -m pip install pyinstaller

install:
- cd src
- pyinstaller --clean -F --distpath=gam $GAMOS-gam.spec
- cp LICENSE gam
- cp whatsnew.txt gam
- cp GamCommands.txt gam
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
    GAM_ARCHIVE=gam-$TRAVIS_BUILD_NUMBER-$GAMOS.zip;
    /c/Program\ Files/7-Zip/7z.exe a -tzip $GAM_ARCHIVE -xr!.svn;
    export GAMVERSION=$TRAVIS_BUILD_NUMBER;
    /c/Program\ Files\ \(x86\)/WiX\ Toolset\ v3.11/bin/candle.exe -arch x64 gam.wxs;
    /c/Program\ Files\ \(x86\)/Wix\ Toolset\ v3.11/bin/light.exe -ext /c/Program\ Files\ \(x86\)/WiX\ Toolset\ v3.11/bin/WixUIExtension.dll gam.wixobj -o gam-$TRAVIS_BUILD_NUMBER-$GAMOS-x64.msi;
  else
    GAM_ARCHIVE=gam-$TRAVIS_BUILD_NUMBER-$GAMOS.tar.xz;
    tar cfJ $GAM_ARCHIVE gam/;
  fi

script:
- gam/gam version
