language: python
dist: precise
osx_image: xcode9.2

python:
 - "2.7"

os:
 - linux
 - osx

before_install:
- pip install pyinstaller
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then GAMOS="linux" ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then GAMOS="macos" ; fi

install:
- pyinstaller --clean -F --distpath=gam src/$GAMOS-gam.spec
- cp src/LICENSE src/gam
- cp src/whatsnew.txt src/gam
- cp src/GamCommands.txt src/gam
- tar cfJ gam-$TRAVIS_BUILd_NUMBER-$GAMOS.tar.xz src/gam/

script: src/dist/gam version
deploy:
  provider: release
  skip_cleanup: true
  file: gam-$TRAVIS_BUILd_NUMBER-$GAMOS.tar.xz
