if: tag IS blank
env:
  - TESTING=FALSE

matrix:
  include:
    - os: linux
      language: python
      dist: precise
      python:
        - "2.7.15"
      env:
        - GAMOS=linux
        - PLATFORM=x86_64
    - os: osx
      language: generic
      osx_image: xcode10.1
      env:
        - GAMOS=macos
        - PLATFORM=x64
      addons:
        homebrew:
          packages:
            python@2
    - os: windows
      language: shell
      env:
        - GAMOS=windows
          PLATFORM=x64
          CINST_ARGS=""
    - os: windows
      language: shell
      env:
        - GAMOS=windows
        - CINST_ARGS=--forcex86
        - PLATFORM=x86
    - os: osx
      language: generic
      osx_image: xcode9.2
      env:
        - GAMOS=macos
        - PLATFORM=x64-sierra-testing
        - TESTING=TRUE
      addons:
        homebrew:
          packages:
            python@2
    - os: linux
      language: python
      dist: precise
      env:
        - GAMOS=linux
        - PLATFORM=i686-precise-testing
        - TESTING=TRUE
  allow_failures:
    -env:
      TESTING=TRUE

before_install:
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
    powershell Install-WindowsFeature Net-Framework-Core;
    cinst -y $CINST_ARGS python2;
    export PATH=$PATH:/c/Python27/scripts;
    cinst -y wixtoolset;
  elif [[ "$PLATFORM" == "i686-precise-testing" ]]; then
    dpkg --add-architecture i386;
    apt install -y python:i386;
    python -V;
  fi
- curl https://bootstrap.pypa.io/get-pip.py | sudo python
- pip install pyinstaller

install:
- cd src
- pyinstaller --clean -F --distpath=gam $GAMOS-gam.spec
- gam/gam version
- export GAMVERSION=`gam/gam version simple`
- cp LICENSE gam
- cp whatsnew.txt gam
- cp GamCommands.txt gam
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
    cp gam-setup.bat gam;
    GAM_ARCHIVE=gam-$GAMVERSION-$GAMOS-$PLATFORM.zip;
    /c/Program\ Files/7-Zip/7z.exe a -tzip $GAM_ARCHIVE gam -xr!.svn;
    mkdir gam-64;
    cp -rf gam/* gam-64/;
    /c/Program\ Files\ \(x86\)/WiX\ Toolset\ v3.11/bin/candle.exe -arch $PLATFORM gam.wxs;
    /c/Program\ Files\ \(x86\)/Wix\ Toolset\ v3.11/bin/light.exe -ext /c/Program\ Files\ \(x86\)/WiX\ Toolset\ v3.11/bin/WixUIExtension.dll gam.wixobj -o gam-$GAMVERSION-$GAMOS-$PLATFORM.msi || true;
    rm *.wixpdb;
  else
    GAM_ARCHIVE=gam-$GAMVERSION-$GAMOS-$PLATFORM.tar.xz;
    tar cfJ $GAM_ARCHIVE gam/;
  fi

script:
- gam/gam version

before_deploy:
- export TRAVIS_TAG="preview"

deploy:
  provider: releases
  api_key:
    secure: bzambMcQwyv/o5c5GrKGCsZHgE5R85tg8sNFvPfpISz3+uosCjnBXas7wvCKzT75XUFi2ztfbYak6HdKf4sGnNHk0saEicB3slH+ghPyZbYzp76yvvduhFO2nWW3/F01tL+Yfqqt4/q8wFaWGjrC5km+6GLVyB4lWA/Uyu49qKnz02uSwyhBD/VFbO7DOQ65a1iWk9HngyMsu0Oi7HIbSjSLtxTHedNfOf3waW0NivTTxYXiYGX/MCu3GWhgIGj47a+H3A6FcQ/9QWvnKgnoixdgPBUz7kDb7ktsWwQsILPGStgH7iMuG49ZlXdEFmqwifBri2wvzmFEevBGZjHcupy1IGrNFRG+IUGKMotio+OkLHlLjuv7ZJtqCz/Vf5SNFgNyMSanx6jKEUJuYvndVg99IRXmYVwHFwPu5BAcJACpU6C0AfyGmmSqqwxCd46uXL62ynxNFpHuRfOqlDnmCTfZgjOciJSlDDpf+Xz9fF7+oCoeCi3mrcZVFjhd3tT6Oxw5HrsDtm0ZNld1cdLidaq8H6vOFgHMd0A9yNYZzTzXTvpmxzkXT4Zc7s+PYKN6z5fRZ+pJeckUjRXblvVEfs5HFSymavcOc5AkRwxpvOsTQMNmlnaJCBo5UNs0K/rVmRi5cFmaiwTcBCY0kTllOBJ4zWsfq8seiokWwNUNK2g=
  file_glob: true
  overwrite: true
  file: gam-$GAMVERSION-*
  skip_cleanup: true
  draft: true
  on:
    repo: jay0lee/GAM
