matrix:
  include:
    - os: linux
      language: python
      dist: precise
      python:
        - "2.7.15"
      env: GAMOS=linux
    - os: osx
      language: generic
      osx_image: xcode10.1
      env: GAMOS=macos
      addons:
        homebrew:
          packages:
            python@2
    - os: windows
      language: shell
      env: GAMOS=windows

before_install:
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
    cinst -y python2;
    PATH=$PATH:/c/Python27/scripts;
  fi
- pip install pyinstaller

install:
- cd src
- pyinstaller --clean -F --distpath=gam $GAMOS-gam.spec
- cp LICENSE gam
- cp whatsnew.txt gam
- cp GamCommands.txt gam
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
    set
    ls -l $ProgramFiles;
    GAM_ARCHIVE=gam-$TRAVIS_BUILD_NUMBER-$GAMOS.zip;
    $ProgramFiles/7-Zip/7z.exe a -tzip $GAM_ARCHIVE -xr!.svn;
  else
    GAM_ARCHIVE=gam-$TRAVIS_BUILD_NUMBER-$GAMOS.tar.xz
    tar cfJ $GAM_ARCHIVE gam/;
  fi

script:
- gam/gam version
