matrix:
  include:
    - os: linux
      language: python
      dist: precise
      python:
        - "2.7.15"
      env: GAMOS=linux
    - os: osx
      language: generic
      osx_image: xcode9.2
      env: GAMOS=macos
      addons:
        homebrew:
          packages:
            python@2
    - os: windows
      language: shell
      env: GAMOS=windows

before_install:
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
    cinst -y python2;
    ls -l /
    ls -al /python2;
    PATH=$PATH:/python2/scripts;
  fi
- pip install pyinstaller

install:
- cd src
- pyinstaller --clean -F --distpath=gam $GAMOS-gam.spec
- cp LICENSE gam
- cp whatsnew.txt gam
- cp GamCommands.txt gam
- tar cfJ gam-$TRAVIS_BUILd_NUMBER-$GAMOS.tar.xz gam/

script:
- gam/gam version

deploy:
  skip_cleanup: true
  file: gam-$TRAVIS_BUILd_NUMBER-$GAMOS.tar.xz
